apiVersion: v1
kind: Service
metadata:
  name: deployment-nodeport-service
spec:
  type: NodePort 
  selector: 
    app: mirat-app
  ports: 
    - name: http-tomcat
      port: 8080
      targetPort: 8080
      nodePort: 31233
