apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirat-app
  template: 
    metadata: 
      name: mirat-app
      labels:  
        app: mirat-app         
    spec:
      containers: 
        - name: mirat-tomcat
          image: tomcat:8.5.41
          ports:
            - containerPort: 8080
